# Generated by Django 3.1.4 on 2022-02-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('family_code', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.familyhead')),
            ],
        ),
    ]
