# Generated by Django 3.1.4 on 2022-02-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='head',
            new_name='familyhead',
        ),
    ]
